[build]
  command = "node build.js && cp mnl-header-original-v2.jpg dist/mnl-header-original-v2.jpg && cp mnl-glance-original-v2.jpg dist/mnl-glance-original-v2.jpg && cp mnl-header-original-v3.png dist/mnl-header-original-v3.png && cp mnl-glance-original-v3.png dist/mnl-glance-original-v3.png && mkdir -p dist/mnl-manager-banners && cp mnl-manager-banners/* dist/mnl-manager-banners/"
  publish = "dist"
